export enum Activators {
	UP = "UP",
	DOWN = "DOWN",
	LEFT = "LEFT",
	RIGHT = "RIGHT",
	L = "L",
	ZL = "ZL",
	ZLF = "ZLF",
	R = "R",
	ZR = "ZR",
	ZRF = "ZRF",
	BACK = "-",
	START = "+",
	HOME = "HOME",
	CAPTURE = "CAPTURE",
	LSL = "LSL",
	RSL = "RSL",
	LSR = "LSR",
	RSR = "RSR",
	LEFT_STICK_CLICK = "L3",
	RIGHT_STICK_CLICK = "R3",
	N = "N",
	E = "E",
	S = "S",
	W = "W",
	LUP = "LUP",
	LDOWN = "LDOWN",
	LLEFT = "LLEFT",
	LRIGHT = "LRIGHT",
	LRING = "LRING",
	RUP = "RUP",
	RDOWN = "RDOWN",
	RLEFT = "RLEFT",
	RRIGHT = "RRIGHT",
	RRING = "RRING",
	MUP = "MUP",
	MDOWN = "MDOWN",
	MLEFT = "MLEFT",
	MRIGHT = "MRIGHT",
	MRING = "MRING",
	LEAN_LEFT = "LEAN_LEFT",
	LEAN_RIGHT = "LEAN_RIGHT",
	TOUCH = "TOUCH",
	MIC = "MIC",
}

export const activatorsList: Array<String> = [
	Activators.UP,
	Activators.DOWN,
	Activators.LEFT,
	Activators.RIGHT,
	Activators.L,
	Activators.ZL,
	Activators.ZLF,
	Activators.R,
	Activators.ZR,
	Activators.ZRF,
	Activators.BACK,
	Activators.START,
	Activators.HOME,
	Activators.CAPTURE,
	Activators.LSL,
	Activators.RSL,
	Activators.LSR,
	Activators.RSR,
	Activators.LEFT_STICK_CLICK,
	Activators.RIGHT_STICK_CLICK,
	Activators.N,
	Activators.E,
	Activators.S,
	Activators.W,
	Activators.LUP,
	Activators.LDOWN,
	Activators.LLEFT,
	Activators.LRIGHT,
	Activators.LRING,
	Activators.RUP,
	Activators.RDOWN,
	Activators.RLEFT,
	Activators.RRIGHT,
	Activators.RRING,
	Activators.MUP,
	Activators.MDOWN,
	Activators.MLEFT,
	Activators.MRIGHT,
	Activators.MRING,
	Activators.LEAN_LEFT,
	Activators.LEAN_RIGHT,
	Activators.TOUCH,
	Activators.MIC,
];