export enum Settings {
	IN_GAME_SENS = "IN_GAME_SENS",
	REAL_WORLD_CALIBRATION = "REAL_WORLD_CALIBRATION",
	ZL_MODE = "ZL_MODE",
	ADAPTIVE_TRIGGER = "ADAPTIVE_TRIGGER",
	LEFT_STICK_MODE = "LEFT_STICK_MODE",
	RIGHT_STICK_MODE = "RIGHT_STICK_MODE",
	TOUCHPAD_MODE = "TOUCHPAD_MODE",
	GYRO_OFF = "GYRO_OFF"
}